import { Box } from "@mui/material";
import React from "react";

const Home = () => {
  return (
    <Box height="100%" width="100%">
      <ul>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
        <li>my</li>
      </ul>
    </Box>
  );
};

export default Home;
